---
- name: configure nginx
  hosts: "{{ host }}"
  become: true
  gather_facts: true
  tasks:
    - name: Install nginx
      ansible.builtin.package:
        name: nginx

    - name: Start nginx
      ansible.builtin.service:
        name: nginx
        state: started